version: '3.8'

services:
  inframon:
    container_name: inframon
    image: inframon:latest
    environment:
      - CONFIG_PATH=/config/config.yaml
    volumes:
      - ../config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
    network_mode: bridge

###version: '3.8'

###services:
###  inframon:
###    container_name: inframon
###    image: inframon:latest
###    environment:
###      - CONFIG_PATH=/config/config.yaml
###    volumes:
###      - ../config:/config
###      - inframon_logs:/inframon/logs
###    network_mode: bridge

###volumes:
###   inframon_logs: