version: '3.8'

services:
  inframon:
    container_name: inframon
    image: inframon:latest
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - CONFIG_PATH=/config/config.yaml
    volumes:
      - ../config:/config
    network_mode: bridge
