icmp:
  - address: "10.91.255.214"
    service: "SomeMachine"
    timeout: 5
    failureTimeout: 10
    retryBuffer: 5
    networkZone: "DMZ"
    instanceType: "VirtualMachine"

http:
  - address: "https://loadbalancer.domain.net"
    service: "service-loadbalancer"
    timeout: 60
    failureTimeout: 10
    skipVerify: true
    retryBuffer: 5
    networkZone: "GATEWAYS"
    instanceType: "LXC"

configuration:
    stdOut: true
    healthCheckTimeout: 5
    discordWebhookDisable: false
    healthCron: "0 */12 * * *"
    healthCronDisable: true    
    healthCronWebhookDisable: false
    healthCronSmtpDisable: false
    discordWebhookUrl: "https://discord.com/api/webhooks/***********************************"
    smtpDisable: false
    logFileSize: "10MB"
    maxLogFileKeep: 5
    smtpHost: "smtp.sendgrid.net"
    smtpPort: "587"
    smtpFrom: "donotreply@domain.net"
    smtpUsername: "USERNAME"
    smtpPassword: "PASSWORD"
    smtpTo: "email@domain.net"
