name: Build, Push Container Image, and Publish SBOM Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Container image
      working-directory: scripts
      run: ./builddocker.sh

    - name: Setup Grype
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_API_KEY }}

    - name: Build and Push Container Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKER_USERNAME }}/inframon:latest

    - name: Generate SBOM Report
      run: |
        mkdir -p sbom_reports
        grype --scope all-layers inframon -o cyclonedx -json> sbom_reports/sbom.json

    - name: Upload SBOM Report
      uses: actions/upload-artifact@v3
      with:
        name: sbom-report
        path: sbom_reports/inframon.json