name: Binary Multi-arch Build for Development

on:
  push:
    branches: [ "dev" ]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gosec-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-fmt=sarif -out=results.sarif ./...'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif

  build-and-test:
    needs: [gitleaks-scan, gosec-scan]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            goos: linux
          - os: macos-latest
            goos: darwin
        exclude:
          - os: macos-latest
            arch: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Display build configuration
      run: |
        echo "Building for OS: ${{ matrix.goos }}, Arch: ${{ matrix.arch }}, on ${{ matrix.os }}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.5

    - name: Build Go binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -o inframon-${{ matrix.goos }}-${{ matrix.arch }} ./src

    - name: Run tests
      run: go test ./...

    - name: Generate SHA256 checksum
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sha256sum inframon-${{ matrix.goos }}-${{ matrix.arch }} > inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256
        elif [ "${{ runner.os }}" == "macOS" ]; then
          shasum -a 256 inframon-${{ matrix.goos }}-${{ matrix.arch }} > inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256
        else
          echo "Unsupported OS for SHA256 generation"
          exit 1
        fi
        echo "SHA256 checksum for inframon-${{ matrix.goos }}-${{ matrix.arch }}:"
        cat inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: inframon-${{ matrix.goos }}-${{ matrix.arch }}
        path: |
          inframon-${{ matrix.goos }}-${{ matrix.arch }}
          inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256

    - name: Print SHA256 checksums
      run: |
        echo "SHA256 checksums for inframon binaries:"
        cat inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256