name: Binary Multi-arch Build, and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        go-version: [1.21.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build Go binary
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -o inframon-${{ matrix.arch }} ./src

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: inframon-${{ matrix.arch }}
        path: inframon-${{ matrix.arch }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CR }}

    - name: Set lowercase repository name
      run: |
        echo "GITHUB_REPOSITORY_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Push binary to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_CR }}
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin
        docker build -t ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:${{ matrix.arch }}-${{ github.sha }} --build-arg ARCH=${{ matrix.arch }} .
        docker push ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:${{ matrix.arch }}-${{ github.sha }}