name: Binary Multi-arch Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        go-version: [1.22.5]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build Go binary
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -o inframon-linux-${{ matrix.arch }} ./src

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: inframon-linux-${{ matrix.arch }}
        path: inframon-linux-${{ matrix.arch }}

    - name: Generate release tag
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "RELEASE_TAG=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
        files: |
          inframon-linux-${{ matrix.arch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_CR }}