name: Build, Push Container Image, Scan, and Publish SBOM Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Build AMD64 Container Image
      run: |
        docker buildx build --platform linux/amd64 -t inframon:latest .

    - name: Run Trivy for AMD64 and Generate SBOM
      run: |
        mkdir -p sbom_reports
        trivy image --format json --output sbom_reports/sbom_amd64.json inframon:latest
        if [ $? -ne 0 ]; then exit 1; fi

    - name: Publish SBOM for AMD64
      uses: actions/upload-artifact@v4
      with:
        name: sbom-report-amd64
        path: sbom_reports/sbom_amd64.json

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CR }}

    - name: Push AMD64 Container Image
      run: |
        docker tag inframon:amd64-latest ghcr.io/${{ github.repository }}/inframon:latest
        docker push ghcr.io/${{ github.repository }}/inframon:latest

  build-and-scan-arm64:
    runs-on: ubuntu-latest
    needs: build-and-scan-amd64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Build ARM64 Container Image
      run: |
        docker buildx build --platform linux/arm64 -t inframon:latest .

    - name: Run Trivy for ARM64 and Generate SBOM
      run: |
        mkdir -p sbom_reports
        trivy image --format json --output sbom_reports/sbom_arm64.json inframon:latest
        if [ $? -ne 0 ]; then exit 1; fi

    - name: Publish SBOM for ARM64
      uses: actions/upload-artifact@v4
      with:
        name: sbom-report-arm64
        path: sbom_reports/sbom_arm64.json

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CR }}

    - name: Push ARM64 Container Image
      run: |
        docker tag inframon:arm64-latest ghcr.io/${{ github.repository }}/inframon:latest
        docker push ghcr.io/${{ github.repository }}/inframon:latest
