name: OCI Build, Scan, Push, and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Build Container Image
      run: |
        docker buildx build --platform linux/${{ matrix.arch }} -t local/inframon:${{ matrix.arch }} --load .

    - name: Run Trivy vulnerability scanner
      id: trivy
      run: |
        mkdir -p scan_results
        if trivy image --exit-code 1 --severity HIGH,CRITICAL --format table --output scan_results/trivy-results-${{ matrix.arch }}.txt local/inframon:${{ matrix.arch }}; then
          echo "scan_status=passed" >> $GITHUB_OUTPUT
        else
          echo "scan_status=failed" >> $GITHUB_OUTPUT
        fi

    - name: Check scan results
      id: scan
      run: |
        if [ "${{ steps.trivy.outputs.scan_status }}" = "passed" ]; then
          echo "No HIGH or CRITICAL vulnerabilities found for ${{ matrix.arch }}"
          echo "scan_passed=true" >> $GITHUB_OUTPUT
        else
          echo "Vulnerabilities found for ${{ matrix.arch }}"
          cat scan_results/trivy-results-${{ matrix.arch }}.txt
          echo "scan_passed=false" >> $GITHUB_OUTPUT
        fi

    - name: Generate SBOM
      run: |
        mkdir -p sbom_reports
        trivy image --format json --output sbom_reports/sbom-${{ matrix.arch }}.json local/inframon:${{ matrix.arch }}

    - name: Set job output
      id: set_output
      run: |
        echo "scan_passed_${{ matrix.arch }}=${{ steps.scan.outputs.scan_passed }}" >> $GITHUB_OUTPUT
        echo "Scan passed for ${{ matrix.arch }}: ${{ steps.scan.outputs.scan_passed }}"

    - name: Save image to tar
      if: steps.scan.outputs.scan_passed == 'true'
      run: |
        mkdir -p image_tars
        docker save local/inframon:${{ matrix.arch }} > image_tars/inframon-${{ matrix.arch }}.tar
        echo "Image saved to tar for ${{ matrix.arch }}"

    - name: Upload image tar
      if: steps.scan.outputs.scan_passed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: inframon-${{ matrix.arch }}-image
        path: image_tars/inframon-${{ matrix.arch }}.tar

    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-results-${{ matrix.arch }}
        path: scan_results/trivy-results-${{ matrix.arch }}.txt

    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: sbom-${{ matrix.arch }}
        path: sbom_reports/sbom-${{ matrix.arch }}.json

  push-images:
    needs: [build-and-scan-container]
    if: needs.build-and-scan-container.outputs.scan_passed_amd64 == 'true' && needs.build-and-scan-container.outputs.scan_passed_arm64 == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set lowercase repository name
      run: |
        echo "GITHUB_REPOSITORY_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "Repository name set to: ${{ env.GITHUB_REPOSITORY_LOWERCASE }}"

    - name: Download amd64 image
      uses: actions/download-artifact@v4
      with:
        name: inframon-amd64-image
        path: image_tars

    - name: Download arm64 image
      uses: actions/download-artifact@v4
      with:
        name: inframon-arm64-image
        path: image_tars

    - name: Check if artifacts exist
      id: check_artifacts
      run: |
        if [ ! -f image_tars/inframon-amd64.tar ] || [ ! -f image_tars/inframon-arm64.tar ]; then
          echo "artifacts_exist=false" >> $GITHUB_OUTPUT
          echo "Error: One or both artifacts are missing. Skipping push."
        else
          echo "artifacts_exist=true" >> $GITHUB_OUTPUT
          echo "Both artifacts found."
        fi

    - name: Debug - List downloaded artifacts
      run: |
        echo "Contents of image_tars directory:"
        ls -l image_tars/

    - name: Log in to GitHub Container Registry
      if: steps.check_artifacts.outputs.artifacts_exist == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CR }}

    - name: Debug - Check Docker Login
      if: steps.check_artifacts.outputs.artifacts_exist == 'true'
      run: |
        echo "Checking Docker login status..."
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_CR }}
        if [ $? -eq 0 ]; then
          echo "Login successful"
        else
          echo "Login failed"
          exit 1
        fi

    - name: Push images to GitHub Packages
      if: steps.check_artifacts.outputs.artifacts_exist == 'true'
      run: |
        # Load images from tar files
        echo "Loading amd64 image..."
        docker load < image_tars/inframon-amd64.tar
        echo "Loading arm64 image..."
        docker load < image_tars/inframon-arm64.tar

        # List loaded images
        echo "Loaded Docker images:"
        docker images

        # Tag images for GitHub Packages
        echo "Tagging images..."
        docker tag local/inframon:amd64 ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:amd64
        docker tag local/inframon:arm64 ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:arm64

        # Push images to GitHub Packages
        echo "Pushing amd64 image..."
        docker push ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:amd64
        if [ $? -ne 0 ]; then
          echo "Failed to push amd64 image"
          exit 1
        fi

        echo "Pushing arm64 image..."
        docker push ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:arm64
        if [ $? -ne 0 ]; then
          echo "Failed to push arm64 image"
          exit 1
        fi

        # Create and push multi-arch manifest
        echo "Creating multi-arch manifest..."
        docker manifest create ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:latest \
          ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:amd64 \
          ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:arm64

        echo "Pushing multi-arch manifest..."
        docker manifest push ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:latest
        if [ $? -ne 0 ]; then
          echo "Failed to push multi-arch manifest"
          exit 1
        fi

    - name: Debug - List GHCR Contents
      if: always()
      run: |
        echo "Listing GHCR contents..."
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_CR }}
        echo "Attempting to pull latest image..."
        docker pull ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:latest || echo "Failed to pull latest image"
        echo "Attempting to pull amd64 image..."
        docker pull ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:amd64 || echo "Failed to pull amd64 image"
        echo "Attempting to pull arm64 image..."
        docker pull ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/inframon:arm64 || echo "Failed to pull arm64 image"
        echo "Listing all Docker images:"
        docker images

    - name: Debug - Check Package Visibility
      if: always()
      run: |
        echo "Checking package visibility..."
        curl -H "Authorization: Bearer ${{ secrets.GH_CR }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/user/packages?package_type=container