name: Binary Multi-arch Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            arch: amd64
          - os: ubuntu-latest
            goos: linux
            arch: arm64
          - os: macos-latest
            goos: darwin
            arch: arm64
        go-version: [1.22.5]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build Go binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -o inframon-${{ matrix.goos }}-${{ matrix.arch }} ./src

    - name: Generate SHA256 checksum
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sha256sum inframon-${{ matrix.goos }}-${{ matrix.arch }} > inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256
        elif [ "${{ runner.os }}" == "macOS" ]; then
          shasum -a 256 inframon-${{ matrix.goos }}-${{ matrix.arch }} > inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256
        else
          echo "Unsupported OS for SHA256 generation"
          exit 1
        fi
        echo "SHA256 checksum for inframon-${{ matrix.goos }}-${{ matrix.arch }}:"
        cat inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: inframon-${{ matrix.goos }}-${{ matrix.arch }}
        path: |
          inframon-${{ matrix.goos }}-${{ matrix.arch }}
          inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256

    - name: Generate release tag
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "RELEASE_TAG=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
        files: |
          inframon-${{ matrix.goos }}-${{ matrix.arch }}
          inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GH_CR }}

    - name: Print SHA256 checksums
      run: |
        echo "SHA256 checksums for inframon binaries:"
        cat inframon-${{ matrix.goos }}-${{ matrix.arch }}.sha256