name: (Development) Build, Push Container Image, Scan, and Publish SBOM Report

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Build Container Image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t inframon:dev .

    - name: Run Trivy for Container Image and Generate SBOM
      run: |
        mkdir -p sbom_reports
        trivy image --format json --output sbom_reports/sbom_latest.json inframon:dev
        if [ $? -ne 0 ]; then exit 1; fi

    - name: Publish SBOMs
      uses: actions/upload-artifact@v4
      with:
        name: sbom-report
        path: sbom_reports/sbom_latest.json

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CR }}

    - name: Push Container Image
      run: |
        docker tag inframon:dev ghcr.io/${{ github.repository }}/inframon:dev
        docker push ghcr.io/${{ github.repository }}/inframon:dev
