name: Build, Scan, Push Container Image, and Publish SBOM Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Container Image
      working-directory: scripts
      run: ./builddocker.sh

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Build and Save Container Image
      uses: docker/build-push-action@v6
      with:
        push: false
        load: true
        tags: ghcr.io/${{ github.repository }}/inframon:latest

    - name: Run Trivy Vulnerability Scanner
      run: |
        trivy image --format table --exit-code 1 --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH 'ghcr.io/${{ github.repository }}/inframon:latest'

    - name: Login to GitHub Container Registry
      if: success()
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Container Image
      if: success()
      run: |
        docker push ghcr.io/${{ github.repository }}/inframon:latest

    - name: Generate SBOM
      if: success()
      run: |
        trivy image --format cyclonedx-json --output sbom-report.json 'ghcr.io/${{ github.repository }}/inframon:latest'

    - name: Publish SBOM
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: sbom-report
        path: sbom-report.json