name: Build, Push Container Image, Scan, and Publish SBOM Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Build the Container Image
      working-directory: scripts
      run: ./builddocker.sh

    - name: Run Trivy to Generate SBOM and Scan for Vulnerabilities
      run: |
        mkdir -p sbom_reports
        trivy image --format json --output sbom_reports/sbom.json ./inframon:latest
        if [ $? -ne 0 ]; then exit 1; fi

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CR }}

    - name: Build and Push Container Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository }}/inframon:latest
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.description=Image for ${{ github.repository }}
          org.opencontainers.image.licenses=MIT

    - name: Publish SBOM
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: sbom-report-${{ matrix.platform }}
        path: sbom-report-${{ matrix.platform }}.json
